const assert=require('node:assert/strict');
const fs=require('node:fs');
const ts=require('./frontend/node_modules/typescript');
const Module=require('module');
const m=new Module('universe-model');
m._compile(ts.transpileModule(fs.readFileSync(__dirname+'/frontend/app/universe-model.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,'universe-model.js');
const {buildUniverseGraph,focusGraph,orderedEvents,eventContext}=m.exports;
const entity=(id,kind,extra={})=>({id,kind,name:id,summary:id,evidence:'passage',confidence:1,reader_safe:true,status:'confirmed',links:[],knowledge:[],...extra});
const u={entities:[entity('person','character',{relations:[{target_id:'event',label:'participated in',evidence:'passage'}]}),entity('other','character'),entity('event','event',{timeline_order:2,relations:[{target_id:'place',label:'occurred at',evidence:'passage'}]}),entity('earlier','event',{timeline_order:1}),entity('unknown','event'),entity('place','location'),entity('hidden','character',{status:'rejected'})],facts:[{category:'event',text:'A meeting',evidence:'passage',order:1,entity_ids:['event','other']},{category:'event',text:'secret fact',evidence:'secret',order:2,entity_ids:['person','hidden']}]};
const graph=buildUniverseGraph(u);
assert(!graph.items.some(n=>n.id==='hidden'||n.name==='secret fact'));
assert(graph.connections.every(e=>graph.items.some(n=>n.id===e.source)&&graph.items.some(n=>n.id===e.target)));
assert(focusGraph(graph,'person').items.some(n=>n.id==='place'));
assert.deepEqual(orderedEvents(graph).known.map(n=>n.id),['earlier','event']);
assert.deepEqual(orderedEvents(graph).unknown.map(n=>n.id),['unknown']);
assert.equal(eventContext(graph,'event').people.length,2);
assert(eventContext(graph,'event').people.find(p=>p.item.id==='other').connection.generic);
assert(!graph.connections.some(e=>e.source==='person'&&e.target==='other'));
assert.deepEqual(buildUniverseGraph({entities:[],facts:[]}),{items:[],connections:[]});
console.log('Graph tests passed: scope, references, focus, chronology, participant uncertainty, empty data.');
