'use client';
import {useEffect,useRef,useState} from 'react';
import {api} from './types';
import {Act} from './writer';
type Notice={id:string;title:string;body:string;created:number;read_at:number|null};
export function Notifications({act}:{act:Act}){
 const [data,setData]=useState<{items:Notice[];unread:number;total:number}>({items:[],unread:0,total:0}),[page,setPage]=useState(1);const dialog=useRef<HTMLDialogElement>(null);
 const refresh=()=>api<typeof data>('/notifications?page='+page).then(setData);
 useEffect(()=>{void refresh().catch(()=>{});const timer=setInterval(()=>{if(!document.hidden)void refresh().catch(()=>{})},30000);return()=>clearInterval(timer)},[page]);
 return <><button className="button" onClick={()=>{dialog.current?.showModal();void act(refresh)}}>Notifications ({data.unread})</button><dialog ref={dialog} className="admin-edit-dialog" aria-label="Notifications"><div className="admin-card form-stack"><h2>Notifications</h2>{data.items.map(n=><article key={n.id}><h3>{n.title}</h3><small>{new Date(n.created*1000).toLocaleString()} · {n.read_at?'Read':'Unread'}</small><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{n.body}</p>{!n.read_at&&<button className="button" onClick={()=>act(async()=>{await api('/notifications/'+n.id+'/read','POST');await refresh()})}>Mark read</button>}</article>)}{!data.items.length&&<p>No notifications yet.</p>}<div className="row"><button className="button" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>{page}</span><button className="button" disabled={page*20>=data.total} onClick={()=>setPage(page+1)}>Next</button></div><button className="button" onClick={()=>dialog.current?.close()}>Close</button></div></dialog></>
}
export function AdminRelationships({act,busy}:{act:Act;busy:boolean}){
 type Person={name:string;email:string;invited:number;accepted:number};
 type Pair={id:string;writer:string;writer_email:string;reader:string;reader_email:string;story:string;status:string;released:number;completed:number;all_released_read:boolean;chapters:{title:string;position:number;progress:number;active:boolean;answers:number;feedback:number}[]};
 const [data,setData]=useState<{relationships:Pair[];writers:Person[];readers:Person[]}|null>(null),[search,setSearch]=useState('');
 const refresh=()=>api<NonNullable<typeof data>>('/admin/relationships').then(setData);
 useEffect(()=>{void act(refresh)},[]);
 return <div className="admin-card"><h2>Writer and beta reader relationships</h2><p>Counts show unique people, so choosing the same beta reader for two stories counts once. Accepted invitations indicate an agreed pairing.</p><button className="button" disabled={busy} onClick={()=>act(refresh)}>Refresh statistics</button><input aria-label="Filter relationships" placeholder="Search writer, beta reader, or story" value={search} onChange={e=>setSearch(e.target.value)}/>{data&&<><div className="admin-stats">{[['Writers',data.writers],['Beta readers',data.readers]].map(([label,people])=><div key={label as string}><h3>{label as string}</h3>{(people as Person[]).filter(p=>(p.name+' '+p.email).toLowerCase().includes(search.toLowerCase())).map(p=><p key={p.email}><strong>{p.name}</strong><br/><small>{p.email}</small><br/>{p.invited} unique {label==='Writers'?'readers invited':'writers choosing this reader'} · {p.accepted} accepted</p>)}</div>)}</div><p>{data.relationships.length} story invitations in total</p>{data.relationships.filter(r=>JSON.stringify([r.writer,r.writer_email,r.reader,r.reader_email,r.story]).toLowerCase().includes(search.toLowerCase())).map(r=><details className="admin-card" key={r.id}><summary><strong>{r.writer} → {r.reader}</strong> · {r.story} · {r.status}</summary><p>{r.writer_email} → {r.reader_email}</p><p>{r.completed} / {r.released} currently accessible chapters read. {r.all_released_read?'All currently released chapters read.':'Reading incomplete or no accessible chapters.'}</p><small>This does not establish completion of the whole story. Reading progress is saved by the reader; feedback is counted separately.</small>{r.chapters.map(c=><p key={c.position}>Chapter {c.position}: {c.title} — {c.progress}% · {c.active?'Accessible':'Access inactive'} · {c.answers} answers · {c.feedback} inline comments</p>)}</details>)}{!data.relationships.length&&<p>No invitations yet.</p>}</>}</div>
}
