'use client';
import {useEffect,useState,useRef} from 'react';
import {api} from './types';
import AccountDashboard from './admin-account';
import {Act} from './writer';
type Account={id:string;name:string;email:string;role:string;suspended:boolean;is_admin:boolean;last_active?:number|null;last_login?:number|null};
type Overview={counts:Record<string,number>;email_enabled:boolean;email_status:Record<string,number>;ai_provider:string};
type Event={id:string;actor:string;action:string;resource:string;created:number;detail?:{reason:string;before:{name:string;role:string;suspended:boolean};after:{name:string;role:string;suspended:boolean}}};
type UserLog={items:{id:string;action:string;resource:string;created:number}[];total:number;first_seen:number|null;last_login:number|null;last_active:number|null;sessions:number};
const timestamp=(v?:number|null)=>v?new Date(v*1000).toLocaleString():'Not recorded yet';
export default function Admin({act,busy,userId}:{act:Act;busy:boolean;userId:string}){
 const [selected,setSelected]=useState<string|null>(null),[detailVersion,setDetailVersion]=useState(0);
 const [overview,setOverview]=useState<Overview|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[events,setEvents]=useState<Event[]>([]),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[editing,setEditing]=useState<Account|null>(null),[reason,setReason]=useState('');
 const [recipients,setRecipients]=useState<Record<string,string>>({}),[noticeTitle,setNoticeTitle]=useState(''),[noticeBody,setNoticeBody]=useState('');
 const [viewing,setViewing]=useState<Account|null>(null),[log,setLog]=useState<UserLog|null>(null),[logPage,setLogPage]=useState(1);
 const activityDialog=useRef<HTMLDialogElement>(null);
 async function showActivity(account:Account,p=1){await act(async()=>{const data=await api<UserLog>('/admin/accounts/'+account.id+'/activity?page='+p);setLog(data);setLogPage(p);setViewing(account)})}
 useEffect(()=>{if(viewing&&!activityDialog.current?.open)activityDialog.current?.showModal()},[viewing]);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(editing&&!dialog.current?.open)dialog.current?.showModal()},[editing]);
 async function refresh(){const [o,a,e]=await Promise.all([api<Overview>('/admin/overview'),api<{items:Account[];total:number}>('/admin/accounts?q='+encodeURIComponent(search)+'&page='+page),api<Event[]>('/admin/activity')]);setOverview(o);setAccounts(a.items);setTotal(a.total);setEvents(e)}
 useEffect(()=>{void act(refresh)},[search,page]);
 return <section>{selected&&<AccountDashboard key={selected+detailVersion} id={selected} act={act} busy={busy} onBack={()=>{setSelected(null);void act(refresh)}} onEdit={a=>{setEditing({...a});setReason('')}} onActivity={a=>showActivity(a)}/>}<div hidden={!!selected}><p className="eyebrow">PRIVATE ADMINISTRATION</p><h1>Website management</h1><p className="muted">Manage accounts, monitor activity, and check delivery status.</p><button className="button" disabled={busy} onClick={()=>act(refresh)}>Refresh</button>
 {overview&&<><div className="admin-stats">{Object.entries(overview.counts).map(([key,value])=><div className="admin-card" key={key}><strong>{value}</strong><span>{key.replaceAll('_',' ')}</span></div>)}</div><div className="admin-card"><h3>Services</h3><p>AI provider: {overview.ai_provider} · Welcome email sending: {overview.email_enabled?'Enabled':'Not enabled'}</p><p>{Object.entries(overview.email_status).map(([k,v])=>`${k}: ${v}`).join(' · ')||'No welcome emails queued.'}</p><small>Provider configuration is shown here; this is not a live availability check.</small></div></>}
 <div className="admin-card"><h2>Accounts</h2><form className="row" onSubmit={e=>{e.preventDefault();setPage(1);setSearch(query)}}><input aria-label="Search accounts" placeholder="Search name or email" value={query} onChange={e=>setQuery(e.target.value)}/><button className="button" disabled={busy}>Search</button></form><p>{total} accounts</p><div className="admin-table"><table><thead><tr><th>Name / email</th><th>Role</th><th>Status / last active</th><th>Actions</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td><button className="text-button" onClick={()=>setSelected(a.id)}>{a.name}</button><br/>{a.email}{a.is_admin&&<small> · Administrator</small>}</td><td>{a.is_admin?'Admin':a.role==='beta'?'Beta reader':a.role==='writer'?'Writer':'Reader'}</td><td>{a.suspended?'Suspended':'Enabled'}<br/><small>{timestamp(a.last_active)}</small></td><td><div className="admin-actions"><button className="button" onClick={()=>setSelected(a.id)}>Open account</button><label><input type="checkbox" aria-label={'Notify '+a.email} checked={!!recipients[a.id]} onChange={e=>setRecipients(old=>{const next={...old};if(e.target.checked)next[a.id]=a.email;else delete next[a.id];return next})}/> Notify</label><button className="button" disabled={busy} onClick={()=>showActivity(a)}>Activity</button><button className="button" disabled={busy||a.id===userId} onClick={()=>{setEditing({...a});setReason('')}}>Edit</button> <button className="button" disabled={busy||a.id===userId} onClick={()=>{if(window.confirm('Sign this account out on all devices?'))void act(async()=>{await api('/admin/accounts/'+a.id+'/revoke-sessions','POST');await refresh()},'Sessions revoked')}}>Sign out devices</button></div></td></tr>)}</tbody></table></div>{!accounts.length&&<p>No matching accounts.</p>}<div className="row"><button className="button" disabled={busy||page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page}</span><button className="button" disabled={busy||page*25>=total} onClick={()=>setPage(page+1)}>Next</button></div></div>
 <form className="admin-card form-stack" onSubmit={e=>{e.preventDefault();if(!window.confirm('Send this notification to '+Object.keys(recipients).length+' selected accounts?'))return;void act(async()=>{await api('/admin/notifications','POST',{recipients:Object.keys(recipients),title:noticeTitle,body:noticeBody});setNoticeTitle('');setNoticeBody('');setRecipients({});await refresh()},'Notification sent')}}><h2>Send an in-app notification</h2><p>Select Notify beside the accounts above. Selections stay selected across search pages.</p><p>Recipients ({Object.keys(recipients).length}): {Object.values(recipients).join(', ')||'None selected'}</p><label>Title<input required maxLength={160} value={noticeTitle} onChange={e=>setNoticeTitle(e.target.value)}/></label><label>Message<textarea required maxLength={3000} value={noticeBody} onChange={e=>setNoticeBody(e.target.value)}/></label><button className="button primary" disabled={busy||!Object.keys(recipients).length||Object.keys(recipients).length>100}>Send notification</button><small>Up to 100 accounts per message. Delivered inside the website, not by email.</small></form>
 </div>
 {viewing&&log&&<dialog ref={activityDialog} className="admin-edit-dialog" aria-labelledby="user-activity-title" onCancel={()=>setViewing(null)}><div className="admin-card form-stack"><h2 id="user-activity-title">Activity: {viewing.name}</h2><p>{viewing.email}</p><p>Last active: {timestamp(log.last_active)}<br/>Last sign-in: {timestamp(log.last_login)}<br/>Unexpired sessions: {log.sessions}</p><p className="muted">Activity tracking began for this account: {timestamp(log.first_seen)}. Earlier activity is unavailable. Last active means the last successful authenticated request, not that the person is currently online.</p>{log.items.map(item=><div key={item.id}><strong>{item.action}</strong><p>{timestamp(item.created)}</p>{item.resource&&<small>Reference: {item.resource}</small>}</div>)}{!log.items.length&&<p>No recorded changes yet.</p>}<div className="row"><button className="button" disabled={busy||logPage===1} onClick={()=>showActivity(viewing,logPage-1)}>Previous</button><span>Page {logPage}</span><button className="button" disabled={busy||logPage*25>=log.total} onClick={()=>showActivity(viewing,logPage+1)}>Next</button></div><button className="button" onClick={()=>setViewing(null)}>Close</button></div></dialog>}
 {editing&&<dialog ref={dialog} className="admin-edit-dialog" aria-labelledby="admin-edit-title" onCancel={()=>setEditing(null)}><form className="admin-card form-stack" onSubmit={e=>{e.preventDefault();void act(async()=>{await api('/admin/accounts/'+editing.id,'PUT',{name:editing.name,role:editing.role,suspended:editing.suspended,reason});setEditing(null);setDetailVersion(v=>v+1);await refresh()},'Account updated and signed out')}}><h2 id="admin-edit-title">Edit {editing.email}</h2><label>Name<input required maxLength={100} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Role<select disabled={editing.is_admin} value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value})}><option value="writer">Writer</option><option value="beta">Beta reader</option><option value="reader">Reader</option></select></label><label>Status<select disabled={editing.is_admin} value={editing.suspended?'suspended':'active'} onChange={e=>setEditing({...editing,suspended:e.target.value==='suspended'})}><option value="active">Active</option><option value="suspended">Suspended</option></select></label><label>Reason for change<textarea required minLength={3} maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>Saving signs the account out of all devices. Suspension preserves its stories and feedback. Email addresses and administrator privileges are managed separately.</p><div className="row"><button className="button primary" disabled={busy}>Save changes</button><button type="button" className="button" onClick={()=>setEditing(null)}>Cancel</button></div></form></dialog>}
 <div hidden={!!selected} className="admin-card"><h2>Administrator activity</h2><p className="muted">Most recent 100 changes</p>{events.map(e=><p key={e.id}>{new Date(e.created*1000).toLocaleString()} — {e.action}{e.detail&&<><br/>{e.detail.reason}<br/><small>{e.detail.before.name} → {e.detail.after.name} · {e.detail.before.role} → {e.detail.after.role} · {e.detail.before.suspended?'Suspended':'Active'} → {e.detail.after.suspended?'Suspended':'Active'}</small></>}<br/><small>Account: {e.resource} · Administrator: {e.actor}</small></p>)}{!events.length&&<p>No administrator changes yet.</p>}</div></section>
}
