'use client';
import {useEffect,useState} from 'react';
import {api} from './types';
import {Act} from './writer';
import AccountConnections from './account-connections';
export type Account={id:string;name:string;email:string;role:string;is_admin:boolean;suspended:boolean;last_active?:number|null;last_login?:number|null};
export type Pair={id:string;story_id:string;writer:string;writer_email:string;reader:string;reader_email:string;story:string;status:string;released:number;completed:number;chapters:{title:string;position:number;progress:number;active:boolean;answers:number;feedback:number}[]};
export type Story={id:string;title:string;words:number;chapters:{id:string;title:string;position:number;state:string;words:number;revision:number}[]};
type Detail={account:Account;stories:Story[];relationships:Pair[];sessions:number};
const date=(v?:number|null)=>v?new Date(v*1000).toLocaleString():'Not recorded yet';
export default function AccountDashboard({id,act,busy,onBack,onEdit,onActivity}:{id:string;act:Act;busy:boolean;onBack:()=>void;onEdit:(a:Account)=>void;onActivity:(a:Account)=>void}){
 const [data,setData]=useState<Detail|null>(null),[tab,setTab]=useState('overview'),[title,setTitle]=useState(''),[body,setBody]=useState('');
 const refresh=()=>api<Detail>('/admin/accounts/'+id+'/dashboard').then(setData);
 useEffect(()=>{void act(refresh);window.scrollTo(0,0)},[id]);
 if(!data)return <section><button className="button" onClick={onBack}>← All accounts</button><p>Loading account…</p></section>;
 const a=data.account,isWriter=a.role==='writer'&&!a.is_admin,pairs=data.relationships,chapters=data.stories.flatMap(s=>s.chapters),unique=new Set(pairs.map(p=>isWriter?p.reader_email:p.writer_email)).size,assigned=pairs.reduce((n,p)=>n+p.released,0),completed=pairs.reduce((n,p)=>n+p.completed,0);
 return <section><button className="text-button" onClick={onBack}>← All accounts</button><div className="account-heading"><div><p className="eyebrow">ACCOUNT DETAILS · {a.is_admin?'ADMIN':isWriter?'WRITER':a.role==='beta'?'BETA READER':'READER'}</p><h1>{a.name}</h1><p className="muted">{a.email}</p></div><span className="badge">{a.suspended?'Suspended':'Enabled'}</span></div><div className="admin-actions"><button className="button" disabled={busy} onClick={()=>act(refresh)}>Refresh</button>{!a.is_admin&&<button className="button" onClick={()=>onEdit(a)}>Edit account</button>}<button className="button" onClick={()=>onActivity(a)}>Activity history</button><button className="button" onClick={()=>setTab('message')}>Send notification</button></div><div className="admin-stats">{(isWriter?[['Stories',data.stories.length],['Words written',data.stories.reduce((n,s)=>n+s.words,0)],['Chapters',chapters.length],['Beta readers invited',unique]]:[['Writers',unique],['Story invitations',pairs.length],['Chapters available',assigned],['Chapters read',completed]]).map(([label,value])=><div className="admin-card" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><nav className="account-tabs">{[['overview','Overview'],['progress',isWriter?'Stories & writing':'Reading assignments'],['people',isWriter?'Beta readers':'Writers'],['message','Notification']].map(([key,label])=><button key={key} className={'button '+(tab===key?'primary':'')} onClick={()=>setTab(key)}>{label}</button>)}</nav>
 {tab==='overview'&&<AccountConnections key={id} account={a} stories={data.stories} pairs={pairs}/>} 
 {tab==='overview'&&<div className="admin-card"><h2>Account overview</h2><p>Last active: {date(a.last_active)}</p><p>Last sign-in: {date(a.last_login)}</p><p>Unexpired sessions: {data.sessions}</p>{isWriter&&<p>{chapters.filter(c=>['verified','released'].includes(c.state)).length} of {chapters.length} chapters verified or released · {chapters.filter(c=>c.state==='draft').length} drafts · {chapters.filter(c=>c.state==='review').length} awaiting review</p>}<p>{pairs.filter(p=>p.status==='accepted').length} accepted story invitations · {pairs.filter(p=>p.status==='pending').length} pending</p><p>{completed} of {assigned} accessible chapter assignments read</p><small>Reading completion reflects saved progress for released chapters. A finished manuscript cannot be inferred from these counts.</small></div>}
 {tab==='progress'&&isWriter&&<>{data.stories.map(s=><div className="admin-card" key={s.id}><h2>{s.title}</h2><p>{s.words.toLocaleString()} words · {s.chapters.length} chapters</p>{s.chapters.map(c=><div className="account-chapter" key={c.id}><strong>{c.position}. {c.title}</strong><span className="badge">{c.state}</span><small>{c.words.toLocaleString()} words · Revision {c.revision}</small></div>)}</div>)}{!data.stories.length&&<p className="admin-card">No stories created yet.</p>}</>}
 {(tab==='people'||(tab==='progress'&&!isWriter))&&<>{pairs.map(p=><div className="admin-card" key={p.id}><div className="account-heading"><div><h2>{isWriter?p.reader:p.writer}</h2><small>{isWriter?p.reader_email:p.writer_email}</small><p>{p.story}</p></div><span className="badge">{p.status}</span></div><p>{p.released?`${p.completed} of ${p.released} chapters read`:'No chapters available yet'}</p>{p.released>0&&<progress className="account-progress" max={p.released} value={p.completed} aria-label="Chapters read"/>}{p.chapters.map(c=><div className="account-chapter" key={c.position}><strong>{c.position}. {c.title}</strong><span>{c.progress}% read {c.active?'':'· Access inactive'}</span><progress className="account-progress" max={100} value={c.progress} aria-label={c.title+' reading progress'}/><small>{c.answers} answers · {c.feedback} inline comments</small></div>)}</div>)}{!pairs.length&&<p className="admin-card">No writer–reader connections yet.</p>}</>}
 {tab==='message'&&<form className="admin-card form-stack" onSubmit={e=>{e.preventDefault();if(window.confirm('Send this notification to '+a.email+'?'))void act(async()=>{await api('/admin/notifications','POST',{recipients:[id],title,body});setTitle('');setBody('')},'Notification sent')}}><h2>Notify {a.name}</h2><p>Delivered to this account’s notification inbox.</p><label>Title<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Message<textarea required maxLength={3000} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="button primary" disabled={busy}>Send notification</button></form>}
 </section>
}
