'use client';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,Eye,MessageSquare,ShieldCheck,Sparkles} from 'lucide-react';
import {api,User} from './types';
import type {Act} from './writer';
import {BetaProfileData,GENRES,ProfileDropdown,SPECIALTIES} from './beta-profile-fields';

export default function BetaProfileOnboarding({user,act,busy,onComplete}:{user:User;act:Act;busy:boolean;onComplete:()=>void}){
 const [step,setStep]=useState(0),[profile,setProfile]=useState<BetaProfileData>({bio:'',genres:[],specialties:[],availability:'available',listed:true});
 const steps=['Profile','Reading preferences','Genres & specialties'];
 const next=()=>setStep(current=>Math.min(2,current+1));
 const submit=()=>void act(async()=>{await api('/beta-profile','PUT',profile);onComplete()},'Your beta reader profile is ready');
 return <main className="beta-onboarding-shell"><section className="beta-onboarding-card"><header><span className="onboarding-icon"><BookOpen size={27}/></span><div><p className="eyebrow">BETA READER SETUP</p><h1>Complete Your Beta Reader Profile</h1><p>Help writers understand your reading taste and match you with the right stories.</p></div></header><ol className="onboarding-progress">{steps.map((label,index)=><li key={label} className={index===step?'active':index<step?'done':''}><span>{index<step?<Check size={14}/>:index+1}</span><small>{label}</small></li>)}</ol>
 {step===0&&<section className="onboarding-step"><div className="onboarding-heading"><Sparkles/><div><h2>Tell writers about you</h2><p>This introduction appears on your profile card.</p></div></div><div className="onboarding-identity"><span>{user.name.split(/\s+/).map(part=>part[0]).slice(0,2).join('').toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.email}</small></div></div><label>About your reading<textarea maxLength={2000} rows={5} value={profile.bio} onChange={event=>setProfile({...profile,bio:event.target.value})} placeholder="What do you enjoy reading, and what kind of perspective do you bring?"/><small>{profile.bio.length} / 2000</small></label><button type="button" className="button primary full" onClick={next}>Next: Reading preferences <ArrowRight size={16}/></button></section>}
 {step===1&&<section className="onboarding-step"><div className="onboarding-heading"><MessageSquare/><div><h2>Set your reading preferences</h2><p>Let writers know whether you are open to new projects.</p></div></div><label>Availability<select value={profile.availability} onChange={event=>setProfile({...profile,availability:event.target.value})}><option value="available">Available for new projects</option><option value="limited">Limited availability</option><option value="unavailable">Not available right now</option></select></label><label className="onboarding-choice"><input type="checkbox" checked={profile.listed} onChange={event=>setProfile({...profile,listed:event.target.checked})}/><Eye size={20}/><span><strong>Let signed-in writers discover my profile</strong><small>Your email and private reading activity are never shown.</small></span></label><div className="onboarding-actions"><button type="button" className="button" onClick={()=>setStep(0)}><ArrowLeft size={16}/>Back</button><button type="button" className="button primary" onClick={next}>Next: Genres & specialties <ArrowRight size={16}/></button></div></section>}
 {step===2&&<section className="onboarding-step"><div className="onboarding-heading"><ShieldCheck/><div><h2>What stories fit you best?</h2><p>Choose at least one genre and one feedback specialty.</p></div></div><ProfileDropdown label="Genres you enjoy" options={GENRES} value={profile.genres} onChange={genres=>setProfile({...profile,genres})} required/><ProfileDropdown label="Feedback specialties" options={SPECIALTIES} value={profile.specialties} onChange={specialties=>setProfile({...profile,specialties})} required/><div className="onboarding-actions"><button type="button" className="button" onClick={()=>setStep(1)}><ArrowLeft size={16}/>Back</button><button type="button" className="button primary" disabled={busy||!profile.genres.length||!profile.specialties.length} onClick={submit}><Check size={16}/>Finish profile</button></div></section>}
 <footer><ShieldCheck size={15}/>You can edit these details later from My Reading Profile.</footer></section></main>
}
