'use client';
import {useState} from 'react';
import {api} from './types';
import type {Act} from './writer';
export default function GuestSupport({act,busy}:{act:Act;busy:boolean}){
 const [open,setOpen]=useState(false),[id,setId]=useState(''),[token,setToken]=useState(''),[created,setCreated]=useState(false),[ticket,setTicket]=useState<{subject:string;status:string;replies:{id:string;author:string;body:string}[]}|null>(null),[reply,setReply]=useState('');
 const check=async(body='')=>{setTicket(await api('/support/guest/check','POST',{id,token,body}));setReply('')};
 return <section className="guest-support"><button className="text-button" onClick={()=>setOpen(!open)} aria-expanded={open}>Can’t sign in? Contact support</button>{open&&<div className="feature-panel"><h3>Account access help</h3><p>No sign-in needed. Don’t include passwords, verification codes, or private manuscripts. Requests do not automatically change account access.</p>{!created&&<form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{const r=await api<{id:string;token:string}>('/support/guest','POST',{email:f.get('email'),subject:f.get('subject'),body:f.get('body')});setId(r.id);setToken(r.token);setCreated(true)},'Support request submitted')}}><label>Contact email<input name="email" type="email" required maxLength={254}/></label><label>Subject<input name="subject" required minLength={3} maxLength={160}/></label><label>What happened?<textarea name="body" required minLength={3} maxLength={10000} rows={4}/></label><button className="button primary" disabled={busy}>Submit support request</button></form>}{created&&<p role="status"><strong>Request submitted.</strong> Save the request ID and private access code below before leaving this page. They let you return here and read support replies. No email confirmation is sent.</p>}<form className="form-stack" onSubmit={e=>{e.preventDefault();void act(()=>check())}}><h3>Check an existing request</h3><label>Request ID<input required value={id} onChange={e=>setId(e.target.value)} autoComplete="off"/></label><label>Private access code<input required value={token} onChange={e=>setToken(e.target.value)} autoComplete="off" spellCheck={false}/></label><small>Keep this code private. Anyone with the ID and code can read and reply to this request.</small><button className="button" disabled={busy}>Check replies</button></form>{ticket&&<div><h3>{ticket.subject}</h3><p>Status: {ticket.status.replaceAll('_',' ')}</p>{ticket.replies.map(r=><article key={r.id} className="admin-card"><strong>{r.author}</strong><p style={{whiteSpace:'pre-wrap'}}>{r.body}</p></article>)}<form className="form-stack" onSubmit={e=>{e.preventDefault();void act(()=>check(reply),'Reply sent')}}><label>Follow-up message<textarea required minLength={3} maxLength={10000} value={reply} onChange={e=>setReply(e.target.value)}/></label><button className="button" disabled={busy}>Send reply</button></form></div>}</div>}</section>
}
