'use client';
import {useEffect,useRef,useState} from 'react';
import {Search,SlidersHorizontal,RotateCcw,RefreshCw,ShieldCheck,X,ChevronLeft,ChevronRight} from 'lucide-react';
import {api} from './types';
import type {Act} from './writer';
type Incident={id:string;category:string;account:string|null;evidence:string;created:number;status:string;severity:string;reason:string};
const label=(s:string)=>s.replaceAll('_',' ');
export default function IncidentDesk({act,busy}:{act:Act;busy:boolean}){
 const [rows,setRows]=useState<Incident[]>([]),[loaded,setLoaded]=useState(false),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[severity,setSeverity]=useState('all'),[category,setCategory]=useState('all'),[more,setMore]=useState(false),[page,setPage]=useState(1),[size,setSize]=useState(25),[selected,setSelected]=useState<Incident|null>(null),[reason,setReason]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 const load=async()=>{setRows(await api<Incident[]>('/admin/ops/incidents'));setLoaded(true)};
 useEffect(()=>{void act(load)},[]);
 useEffect(()=>{setPage(1)},[query,status,severity,category,size]);
 useEffect(()=>{if(selected&&!dialog.current?.open)dialog.current?.showModal()},[selected]);
 const filtered=rows.filter(r=>(status==='all'||r.status===status)&&(severity==='all'||r.severity===severity)&&(category==='all'||r.category===category)&&[r.id,r.account||'',label(r.category),r.evidence].join(' ').toLowerCase().includes(query.toLowerCase()));
 const pages=Math.max(1,Math.ceil(filtered.length/size)),current=Math.min(page,pages),shown=filtered.slice((current-1)*size,current*size);
 const reset=()=>{setQuery('');setStatus('all');setSeverity('all');setCategory('all');setPage(1)};
 const close=()=>{dialog.current?.close();setSelected(null)};
 return <section className="incident-desk"><div className="desk-heading"><div><p className="eyebrow">PLATFORM SAFETY</p><h1>Incidents</h1><p>Investigate operational issues with a clear, auditable trail.</p></div><button className="button primary" disabled={busy} onClick={()=>act(load)}><RefreshCw size={15}/>Refresh incidents</button></div>
 <div className="desk-metrics">{[['Recorded',rows.length],['Open',rows.filter(r=>r.status==='open').length],['Investigating',rows.filter(r=>['acknowledged','investigating','escalated'].includes(r.status)).length],['High / critical',rows.filter(r=>['high','critical'].includes(r.severity)&&r.status!=='resolved').length]].map(([name,n])=><div key={name}><span>{name}</span><strong>{n}</strong></div>)}</div>
 <div className="desk-surface"><div className="desk-filters"><label className="desk-search"><Search size={17}/><input aria-label="Search incidents" placeholder="Search incidents, accounts or IDs" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter incident status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{['open','acknowledged','investigating','escalated','resolved'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select><select aria-label="Filter severity" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="all">All severities</option>{['low','medium','high','critical'].map(s=><option key={s}>{s}</option>)}</select><button className={'button '+(more?'primary':'')} aria-expanded={more} onClick={()=>setMore(!more)}><SlidersHorizontal size={15}/>More filters</button><button className="button" onClick={reset}><RotateCcw size={15}/>Reset</button></div>
 {more&&<div className="desk-extra"><label>Incident category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{Array.from(new Set(rows.map(r=>r.category))).map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><p>Search includes affected account IDs and recorded operational evidence.</p></div>}
 <div className="desk-pagination"><span>{loaded?`${filtered.length} matching incidents`:'Loading incidents…'}</span><label>Rows per page<select value={size} onChange={e=>setSize(+e.target.value)}>{[10,25,50].map(n=><option key={n}>{n}</option>)}</select></label><span>{filtered.length?(current-1)*size+1:0}–{Math.min(current*size,filtered.length)} of {filtered.length}</span><button className="icon-button" aria-label="Previous incident page" disabled={current===1} onClick={()=>setPage(current-1)}><ChevronLeft size={17}/></button><button className="icon-button" aria-label="Next incident page" disabled={current===pages} onClick={()=>setPage(current+1)}><ChevronRight size={17}/></button></div>
 <div className="desk-table"><table><thead><tr><th>Incident</th><th>Affected account</th><th>Category</th><th>Created</th><th>Severity</th><th>Status</th><th>Incident ID</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td><button className="desk-title" onClick={()=>{setSelected({...r});setReason('')}}>{label(r.category)}</button><small className="desk-evidence" title={r.evidence}>{r.evidence}</small></td><td>{r.account?<span className="desk-account" title={r.account}><span className="desk-avatar">{r.account.slice(0,2).toUpperCase()}</span><span>{r.account.slice(0,8)}…</span></span>:<span className="muted">Not identified</span>}</td><td><span className="desk-tag">{r.category.startsWith('request')?'Access & service':r.category.includes('invitation')?'Invitations':r.category.includes('validation')?'Story safety':'AI processing'}</span></td><td className="desk-date">{new Date(r.created*1000).toLocaleDateString()}<small>{new Date(r.created*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></td><td><span className={'severity-dot severity-'+r.severity}>{r.severity}</span></td><td><span className={'status-pill status-'+r.status}>{label(r.status)}</span></td><td><code title={r.id}>{r.id.slice(0,8)}</code></td><td><button className="button small" onClick={()=>{setSelected({...r});setReason('')}}>Review</button></td></tr>)}</tbody></table></div>
 {loaded&&!shown.length&&<div className="desk-empty"><ShieldCheck size={34}/><h2>{rows.length?'No incidents match these filters':'No incidents recorded'}</h2><p>{rows.length?'Try another search or reset your filters.':'Access denials and processing failures will appear here when recorded.'}</p>{rows.length>0&&<button className="button" onClick={reset}>Reset filters</button>}</div>}
 <div className="desk-footer"><ShieldCheck size={15}/><span>Operational evidence only. Private manuscripts, feedback and predictions remain hidden.</span><small>Most recent monitored events</small></div></div>
 <dialog ref={dialog} className="incident-dialog" onCancel={()=>setSelected(null)}>{selected&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void act(async()=>{await api('/admin/ops/incidents/'+selected.id,'PUT',{status:selected.status==='open'?'acknowledged':selected.status,severity:selected.severity,reason});close();await load()},'Incident updated')}}><div className="row between"><div><p className="eyebrow">INCIDENT REVIEW</p><h2>{label(selected.category)}</h2></div><button type="button" className="icon-button" aria-label="Close incident" onClick={close}><X size={20}/></button></div><p className="desk-reference">{selected.id}</p><div className="desk-case-evidence"><strong>Operational evidence</strong><p>{selected.evidence}</p><small>Affected account: {selected.account||'Not identified'}</small></div>{selected.reason&&<p><strong>Previous note:</strong> {selected.reason}</p>}<div className="form-grid"><label>Status<select value={selected.status==='open'?'acknowledged':selected.status} onChange={e=>setSelected({...selected,status:e.target.value})}>{['acknowledged','investigating','escalated','resolved'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Severity<select value={selected.severity} onChange={e=>setSelected({...selected,severity:e.target.value})}>{['low','medium','high','critical'].map(s=><option key={s}>{s}</option>)}</select></label></div><label>Investigation note<textarea required minLength={3} maxLength={1000} rows={4} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain your findings or the next action…"/></label><small>Do not include private manuscript text. This action is recorded in the audit log.</small><div className="row"><button className="button primary" disabled={busy||reason.trim().length<3}>Save action</button><button type="button" className="button" onClick={close}>Cancel</button></div></form>}</dialog>
 </section>
}
