'use client';
import {useState,useEffect} from 'react';
import {api,Snapshot,Universe,Chapter,Analytic,User} from './types';
import type {Act} from './writer';
import PublicInteraction from './public-interaction';
import {UniverseView} from './universe';

export function Explorer({snapshot,onChange,act,busy}:{snapshot:Snapshot;onChange:(u:Universe)=>void;act:Act;busy:boolean}){
 const [preview,setPreview]=useState<Universe|null>(null);
 return <><div className="studio-switch"><button className={'button '+(!preview?'primary':'')} onClick={()=>setPreview(null)}>Writer view</button><button className={'button '+(preview?'primary':'')} disabled={busy||snapshot.status!=='verified'} onClick={()=>act(async()=>setPreview(await api('/snapshots/'+snapshot.id+'/preview')))}>Beta reader preview</button><small>{snapshot.status!=='verified'?'Verify this chapter to enable reader preview.':'Chapter-specific state · private knowledge filtered on the server'}</small></div><UniverseView key={snapshot.id+Boolean(preview)} universe={preview||snapshot.universe} onChange={onChange} reader={Boolean(preview)} frozen={snapshot.status==='verified'}/></>
}
export function PublishControl({chapter,act,busy}:{chapter:Chapter;act:Act;busy:boolean}){
 const [active,setActive]=useState(false);
 useEffect(()=>{void act(async()=>{const p=await api<{active:boolean}>('/chapters/'+chapter.id+'/publication');setActive(p.active)})},[chapter.id]);
 return <section className="feature-panel"><p className="eyebrow">PUBLIC DISCOVERY · AUTHOR CONTROLLED</p><h2>Publish this chapter</h2><p>Publishing makes the verified chapter available to all signed-in readers. Beta invitations remain private.</p><button className="button" disabled={busy||chapter.snapshot?.status!=='verified'} onClick={()=>{if(window.confirm(active?'Remove this chapter from public discovery?':'Publish this verified chapter for all readers?'))void act(async()=>{const r=await api<{active:boolean}>('/chapters/'+chapter.id+'/publication','PUT',{snapshot_id:chapter.snapshot!.id,active:!active});setActive(r.active)},'Publication updated')}}>{active?'Unpublish chapter':'Publish verified chapter'}</button></section>
}
export function IntelligenceChart({analytics,storyId,act}:{analytics:Analytic[];storyId:string;act:Act}){
 const [observations,setObservations]=useState<{snapshot_id:string;kind:string;target:string;value:number;reader_id:string;created:number}[]>([]),[target,setTarget]=useState('');
 useEffect(()=>{void act(async()=>{const d=await api<{observations:typeof observations}>('/stories/'+storyId+'/insights');setObservations(d.observations)})},[storyId]);
 const [metric,setMetric]=useState('predictability'),[revision,setRevision]=useState('all');
 const rows=analytics.filter(a=>revision==='all'||String(a.revision)===revision);
 return <section className="feature-panel"><p className="eyebrow">MEASURED HUMAN FEEDBACK</p><h1>Reader Intelligence Lab</h1><p>Compare chapter snapshots and beta-reader groups. Different groups are not a controlled experiment.</p><div className="studio-switch"><label>Draft revision<select value={revision} onChange={e=>setRevision(e.target.value)}><option value="all">All tested revisions</option>{Array.from(new Set(analytics.map(a=>a.revision))).sort((a,b)=>a-b).map(v=><option key={v} value={v}>Revision {v}</option>)}</select></label><label>Measure<select value={metric} onChange={e=>setMetric(e.target.value)}><option value="predictability">Predictability</option><option value="tension">Emotional tension</option><option value="confidence">Prediction / response confidence</option><option value="emotion_match">Intended emotion match</option><option value="trust">Character trust</option><option value="confusion">Confusion</option><option value="suspicion">Suspicion</option></select></label>{["trust","confusion","suspicion"].includes(metric)&&<label>Character or topic<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose a target</option>{Array.from(new Set(observations.filter(o=>o.kind===metric).map(o=>o.target))).map(t=><option key={t}>{t}</option>)}</select></label>}</div>{!rows.length&&<p>No tested chapters yet.</p>}{rows.map(a=>{const latest=new Map(observations.filter(o=>o.snapshot_id===a.snapshot_id&&o.kind===metric&&o.target===target).sort((a,b)=>a.created-b.created).map(o=>[o.reader_id,o.value]));const value=["trust","confusion","suspicion"].includes(metric)?(latest.size?Math.round(Array.from(latest.values()).reduce((n,v)=>n+v,0)/latest.size):null):metric==='confidence'?(a.responses.length?Math.round(a.responses.reduce((n,r)=>n+r.confidence,0)/a.responses.length):null):metric==='tension'?a.tension:metric==='emotion_match'?a.emotion_match:a.predictability;return <div className="lab-metric" key={a.snapshot_id}><div className="row between"><strong>Chapter {a.chapter} · {a.title}</strong><span>{value===null?'No responses':value+'%'}</span></div><progress max={100} value={value??0} aria-label={`${a.title} ${metric}`}/><small>Revision {a.revision} · {a.respondents} respondents{metric==='predictability'?` · Author target: ${a.intent.desired_predictability??'not set'} · Exact phrase match, not AI correctness judgment`:''}</small></div>})}</section>
}
export {default as IncidentCenter} from './incident-desk';

type PublicStory={id:string;title:string;description:string;author:string;genre:string;cover:string;chapters:{id:string;title:string;position:number;saved:boolean;progress:number}[]};
type PublicChapter={id:string;title:string;content:string;universe:Universe;saved:{progress?:number;bookmark?:number;theory?:string}};
export function Discovery({user,onUser,act,busy}:{user:User;onUser:(u:User)=>void;act:Act;busy:boolean}){
 const [stories,setStories]=useState<PublicStory[]>([]),[q,setQ]=useState(''),[genre,setGenre]=useState('all'),[shelf,setShelf]=useState(false),[reading,setReading]=useState<PublicChapter|null>(null),[size,setSize]=useState(20),[theme,setTheme]=useState('parchment'),[font,setFont]=useState('Georgia'),[maps,setMaps]=useState(false),[focus,setFocus]=useState(false),[recap,setRecap]=useState<{points:{text:string;evidence:string}[]}|null>(null);
 const load=()=>api<PublicStory[]>('/discover').then(setStories);
 useEffect(()=>{void act(load);try{const p=JSON.parse(localStorage.getItem('kathha-reading')||'{}');setSize(p.size||20);setTheme(p.theme||'parchment');setFont(p.font||'Georgia')}catch{}},[]);
 useEffect(()=>{localStorage.setItem('kathha-reading',JSON.stringify({size,theme,font}))},[size,theme,font]);
 const save=async(data:PublicChapter['saved'])=>{if(!reading)return;const next={progress:0,bookmark:0,theory:'',...reading.saved,...data};await api('/public/read/'+reading.id,'PUT',next);setReading({...reading,saved:next});await load()};
 if(reading)return <section className={focus?"focus-reading":""}><div className="studio-switch"><button className="button" onClick={()=>{setReading(null);setMaps(false);setRecap(null)}}>← Discovery</button><label>Text size<input type="range" min={16} max={30} value={size} onChange={e=>setSize(+e.target.value)}/></label><label>Font<select value={font} onChange={e=>setFont(e.target.value)}><option>Georgia</option><option>Arial</option></select></label><label>Reading theme<select value={theme} onChange={e=>setTheme(e.target.value)}>{['parchment','light','dark'].map(t=><option key={t}>{t}</option>)}</select></label><button className="button" onClick={()=>setFocus(!focus)}>{focus?"Exit focus mode":"Focus reading"}</button><button className="button" disabled={(reading.saved.progress||0)<100} onClick={()=>act(async()=>{if(!maps){const fresh=await api<PublicChapter>("/public/read/"+reading.id);setReading(fresh)}setMaps(!maps)})}>{maps?'Back to reading':'Chapter character map'}</button><button className="button" onClick={()=>document.getElementById('public-paragraph-'+(reading.saved.bookmark||0))?.scrollIntoView()}>Go to bookmark</button></div>{maps?<UniverseView universe={reading.universe} reader/>:<article className={'public-reading reading-'+theme} style={{fontFamily:font,fontSize:size}}><p className="eyebrow">PUBLISHED CHAPTER</p><h1>{reading.title}</h1>{reading.content.split('\n\n').map((p,i)=><div key={i} id={'public-paragraph-'+i}><p>{p}</p><button className="text-button" disabled={busy} onClick={()=>act(()=>save({bookmark:i,progress:Math.round(100*i/Math.max(1,reading.content.split('\n\n').length))}),'Bookmark saved')}>{reading.saved.bookmark===i?'Bookmarked':'Bookmark here'}</button></div>)}<button className="button primary" disabled={busy} onClick={()=>act(()=>save({progress:100}),'Reading progress saved')}>Mark chapter read</button></article>}<section className='feature-panel'><h2>Chapter recap</h2><button className='button' disabled={busy||(reading.saved.progress||0)<100} onClick={()=>act(async()=>setRecap(await api('/public/read/'+reading.id+'/recap','POST')))}>Generate recap of completed chapter</button><small>AI interpretation of writer-confirmed facts from this chapter only.</small>{recap?.points.map((p,i)=><div key={i}><p>{p.text}</p><details><summary>Chapter evidence</summary><blockquote>{p.evidence}</blockquote></details></div>)}</section>{user.preferences.interactive_reading&&<section className="feature-panel"><h2>Your private theory · optional</h2><textarea value={reading.saved.theory||''} onChange={e=>setReading({...reading,saved:{...reading.saved,theory:e.target.value}})}/><button className="button" disabled={busy} onClick={()=>act(()=>save({}),'Theory saved')}>Save theory</button></section>}{user.preferences.interactive_reading&&<PublicInteraction key={reading.id} chapterId={reading.id} complete={(reading.saved.progress||0)>=100} act={act} busy={busy}/>}</section>;
 const preferredGenres=new Set(stories.filter(s=>s.chapters.some(c=>c.saved)).map(s=>s.genre));
 const filtered=stories.filter(s=>(genre==='all'||s.genre===genre)&&(!shelf||s.chapters.some(c=>c.saved))&&[s.title,s.author,s.description].join(' ').toLowerCase().includes(q.toLowerCase())).sort((a,b)=>Number(preferredGenres.has(b.genre))-Number(preferredGenres.has(a.genre)));
 return <><div className="page-heading"><div><p className="eyebrow">FIND YOUR NEXT CHAPTER</p><h1>Reader discovery</h1><p>Stories their writers chose to share.</p></div></div><div className="studio-switch"><input aria-label="Search published stories" placeholder="Search stories or authors" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Genre" value={genre} onChange={e=>setGenre(e.target.value)}><option value="all">All genres</option>{Array.from(new Set(stories.map(s=>s.genre))).map(g=><option key={g}>{g}</option>)}</select><button className={'button '+(shelf?'primary':'')} onClick={()=>setShelf(!shelf)}>{shelf?'My library':'Show my library'}</button></div><p className="muted">Suggestions prioritize genres already in your library.</p><div className="story-grid">{filtered.map(s=><article className="story-card" key={s.id}><div className="book-jacket jacket-1" style={s.cover?{backgroundImage:`linear-gradient(#0005,#000a),url(${s.cover})`,backgroundSize:'cover'}:undefined}><span className="jacket-genre">{s.genre}</span><strong>{s.title}</strong><span>{s.author}</span></div><div className="story-card-body"><h2>{s.title}</h2><p>{s.description}</p>{s.chapters.map(c=><button className="text-button" key={c.id} onClick={()=>act(async()=>{setReading(await api('/public/read/'+c.id));setMaps(false)})}>Chapter {c.position}: {c.title} · {c.progress}%</button>)}</div></article>)}</div>{!filtered.length&&<div className="empty inset"><h2>No published stories here yet</h2><p>Private manuscripts never appear automatically.</p></div>}<section className="feature-panel"><label className="checkbox"><input type="checkbox" checked={user.preferences.interactive_reading||false} onChange={e=>{const checked=e.target.checked;void act(async()=>onUser(await api('/preferences','PUT',{interactive_reading:checked})))}}/>Optional interactive reading</label><p>Off means uninterrupted reading: no mandatory questions or predictions.</p></section></>
}
