'use client';
import {useState} from 'react';
import {api} from './types';
import type {Act} from './writer';
export default function PublicInteraction({chapterId,complete,act,busy}:{chapterId:string;complete:boolean;act:Act;busy:boolean}){
 const [data,setData]=useState<{prior:{chapter:number;theory:string}[];reveals:{name:string;summary:string;evidence:string}[]}|null>(null),[comments,setComments]=useState<{id:string;author:string;body:string}[]|null>(null),[body,setBody]=useState('');
 const load=()=>api<{id:string;author:string;body:string}[]>('/public/read/'+chapterId+'/discussion').then(setComments);
 return <section className="feature-panel"><h2>After the chapter · optional</h2><p>Compare your earlier theories with confirmed reveals, or join this chapter’s discussion. These open only after you finish reading.</p><div className="studio-switch"><button className="button" disabled={busy||!complete} onClick={()=>act(async()=>setData(await api('/public/read/'+chapterId+'/comparison')))}>Compare theories & reveals</button><button className="button" disabled={busy||!complete} onClick={()=>act(load)}>Open chapter discussion</button></div>{data&&<div className="analytics-grid"><div><h3>Your earlier theories</h3>{data.prior.map((p,i)=><blockquote key={i}>Chapter {p.chapter}: {p.theory}</blockquote>)}{!data.prior.length&&<p>No earlier theories saved.</p>}</div><div><h3>Reveals confirmed for this chapter</h3>{data.reveals.map((r,i)=><article key={i}><strong>{r.name}</strong><p>{r.summary}</p><blockquote>{r.evidence}</blockquote></article>)}{!data.reveals.length&&<p>No reader-safe reveals recorded for this chapter.</p>}<small>Side-by-side comparison; correctness is not automatically scored.</small></div></div>}{comments&&<><h3>Chapter discussion</h3><p>Discuss only this chapter and earlier events. Do not post future spoilers.</p>{comments.map(c=><article className="response-card" key={c.id}><strong>{c.author}</strong><p>{c.body}</p></article>)}{!comments.length&&<p>No comments yet.</p>}<form className="form-stack" onSubmit={e=>{e.preventDefault();void act(async()=>{await api('/public/read/'+chapterId+'/discussion','POST',{body});setBody('');await load()},'Comment posted')}}><label>Comment<textarea required minLength={3} maxLength={2000} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="button" disabled={busy}>Post to chapter discussion</button></form></>}</section>
}
