CREATE TABLE IF NOT EXISTS google_identities (
 subject VARCHAR(255) PRIMARY KEY,
 user_id VARCHAR(36) NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS google_flows (
 state_hash VARCHAR(64) PRIMARY KEY,
 browser_hash VARCHAR(64) NOT NULL,
 verifier VARCHAR(128) NOT NULL,
 role VARCHAR(20) NOT NULL,
 expires DOUBLE PRECISION NOT NULL
);
